name: build-deploy-licensing-service
run-name: "licensing service test, build and deployment"
on: [push]
jobs:
build-and-test:
  runs-on: ubuntu-latest
  steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: build application
      run : make
