name: build-deploy-licensing-service
run-name: "licensing service test, build and deployment"
on: 
 push:
jobs:
 build-and-test:
  runs-on: ubuntu-latest
  steps:
  - name: Setup Java JDK
    uses: actions/setup-java@v1.4.4
    with:
     java-version: 17
  - name: checkout repo
    uses: actions/checkout@v3
  - name: build application
    run : make build
  - name: Upload Build Artifact
    uses: actions/upload-artifact@v3.1.2
    with:
     name: dev-0.0.1-SNAPSHOT.jar
     path: target
 deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
        # Artifact name
         name: dev-0.0.1-SNAPSHOT.jar

